"""Regenerate native vector paths and supersampled icons from the supplied SVGs.
Run: python3 scripts/generate_brand.py (requires Pillow).
The source artwork uses only M/L/Z paths; reject other commands explicitly.
"""
from pathlib import Path
import json
import re
import shutil
import xml.etree.ElementTree as ET
from PIL import Image, ImageDraw, ImageChops

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'web/public/brand'
NS = {'s': 'http://www.w3.org/2000/svg'}
svg = ET.parse(SOURCE / 'route-logo-light.svg').getroot()
paths = svg.findall('s:path', NS)

def polygons(d):
    assert not re.search(r'[A-KN-Y a-kn-y]', d.replace(' ', '')), 'Unsupported SVG command'
    return [[tuple(map(float, pair)) for pair in re.findall(r'([\d.]+)\s+([\d.]+)', part)] for part in d.split('Z') if part.strip()]

shutil.copyfile(SOURCE / 'route-logo-adaptive.svg', ROOT / 'web/public/favicon.svg')
for source in SOURCE.glob('*.svg'):
    shutil.copyfile(source, ROOT / 'mobile/assets/brand' / source.name)

# Flutter renders the exact SVG geometry as vectors, without a runtime parser.
lines = ["// Generated by scripts/generate_brand.py. Do not edit by hand.", "import 'package:flutter/material.dart';", '']
for name, path in zip(['routeMarkPath', 'routeGreenPath'], paths):
    lines.extend([f'final {name} = Path()', '  ..fillType = PathFillType.evenOdd'])
    for polygon in polygons(path.attrib['d']):
        for i, (x, y) in enumerate(polygon):
            lines.append(f"  ..{'moveTo' if i == 0 else 'lineTo'}({x:g}, {y:g})")
        lines.append('  ..close()')
    lines[-1] += ';'
(ROOT / 'mobile/lib/widgets/route_logo_paths.dart').write_text('\n'.join(lines) + '\n')

def render(destination, size, fraction=.78, background='#0a1315'):
    # Rasterize at 4x and downsample once to preserve thin road markings.
    n = size * 4
    scale = n * fraction / 680
    ox, oy = (n - 680 * scale) / 2, (n - 486 * scale) / 2
    result = Image.new('RGBA', (n, n), background or (0, 0, 0, 0))
    for index, path in enumerate(paths):
        mask = Image.new('1', (n, n))
        for polygon in polygons(path.attrib['d']):
            piece = Image.new('1', (n, n))
            ImageDraw.Draw(piece).polygon([(ox+x*scale, oy+y*scale) for x,y in polygon], fill=1)
            mask = ImageChops.logical_xor(mask, piece)
        if index == 0:
            fill = Image.new('RGBA', (n, n), '#F8FAFC')
        else:
            # SVG objectBoundingBox gradient: (0%,25%) -> (100%,75%).
            pts = [p for poly in polygons(path.attrib['d']) for p in poly]
            x0, y0 = min(p[0] for p in pts), min(p[1] for p in pts)
            w, h = max(p[0] for p in pts)-x0, max(p[1] for p in pts)-y0
            fill = Image.new('RGBA', (256, 256))
            pixels = fill.load()
            for y in range(256):
                for x in range(256):
                    ux = ((x / 255 * n - ox) / scale - x0) / w
                    uy = ((y / 255 * n - oy) / scale - y0) / h
                    t = max(0, min(1, (ux + .5*(uy-.25))/1.25))
                    pixels[x,y] = tuple(round(a+(b-a)*t) for a,b in zip((99,232,59),(160,255,98))) + (255,)
            fill = fill.resize((n,n), Image.Resampling.BILINEAR)
        result.paste(fill, (0, 0), mask.convert('L'))
    result = result.resize((size,size), Image.Resampling.LANCZOS)
    if background:
        result = result.convert('RGB')
    destination.parent.mkdir(parents=True, exist_ok=True)
    result.save(destination)

for name, size, fraction in [('pwa-192.png',192,.78),('pwa-512.png',512,.78),('maskable-512.png',512,.64),('apple-touch-icon.png',180,.78)]:
    render(ROOT / 'web/public' / name, size, fraction)
res = ROOT / 'mobile/android/app/src/main/res'
for density, size, factor in [('mdpi',48,1),('hdpi',72,1.5),('xhdpi',96,2),('xxhdpi',144,3),('xxxhdpi',192,4)]:
    render(res / f'mipmap-{density}/ic_launcher.png', size)
    render(res / f'drawable-{density}/launch_logo.png', round(192*factor), .85, None)
render(res / 'drawable-nodpi/launch_icon.png', 864, .60, None)
icons = ROOT / 'mobile/ios/Runner/Assets.xcassets/AppIcon.appiconset'
for item in json.loads((icons / 'Contents.json').read_text())['images']:
    render(icons / item['filename'], round(float(item['size'].split('x')[0])*float(item['scale'][:-1])))
launch = ROOT / 'mobile/ios/Runner/Assets.xcassets/LaunchImage.imageset'
for factor in [1,2,3]:
    render(launch / ('LaunchImage' + (f'@{factor}x' if factor>1 else '') + '.png'), 192*factor, .85, None)
print('Generated Flutter vector geometry, web icons, and Android/iOS launch assets.')
