import { BrainCircuit, CloudOff, PackageX, ShieldAlert, Wifi } from 'lucide-react'
import { Link } from 'react-router-dom'
import { HOME } from '../../components/shell/nav'
import { Badge, Button, Callout, Card, CardHeader, Field, PageHeader, Select, Stat, toast } from '../../components/ui'
import { MODE_LABELS, type PredictionMode } from '../../domain/intelligence'
import { fmtClock } from '../../domain/time'
import { ops, useDevice, useNetwork, useSession, useView } from '../../store'

export function Resilience() {
  const d = useView()
  const user = useSession((s) => s.user)!
  const net = useNetwork()
  const simulated = useSession((s) => s.simulateOffline)
  const setOffline = useSession((s) => s.setSimulateOffline)
  const flaky = useDevice((s) => s.flakyUploads)
  const conflict = useDevice((s) => s.conflict)
  const retry = useDevice((s) => s.retry)
  const mode = d.intelligence?.mode ?? 'READY'
  const field = user.role === 'DRIVER' || user.role === 'LOADER'
  const prefix = HOME[user.role]
  const relevant = d.issues.filter((i) => !i.resolved && (user.role === 'DISPATCHER' || user.role === 'DRIVER' && i.vehicleId === user.assignedVehicle || user.role === 'STORE_MANAGER' && i.orderIds?.some((id) => d.orders.some((o) => o.id === id && o.outletId === user.assignedOutlet)) || user.role === 'LOADER' && (i.vehicleId ? d.vehicles.some((v) => v.id === i.vehicleId && v.depot === user.depot) : i.orderIds?.some((id) => d.orders.some((o) => o.id === id && d.outlets.some((out) => out.id === o.outletId && out.depot === user.depot))))))
  const failed = net.queue.filter((q) => q.status === 'failed').length
  return <>
    <PageHeader eyebrow="Continuity & recovery" title="When the plan breaks" subtitle="See what is affected, what remains available, and the next safe action." actions={<Link to="/workflow"><Button variant="secondary">Return to workflow</Button></Link>} />
    <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Connection" value={net.online ? 'Online' : 'Offline'} tone={net.online ? 'success' : 'warning'} /><Stat label="Saved on device" value={net.pending} sub="waiting to sync" /><Stat label="Failed uploads" value={failed} tone={failed ? 'attention' : 'neutral'} /><Stat label="Open exceptions" value={relevant.length} tone={relevant.length ? 'attention' : 'neutral'} /></div>
    <div className="grid gap-5 lg:grid-cols-2">
      <Card className="p-5"><h2 className="flex items-center gap-2 font-semibold"><CloudOff className="size-5 text-info" /> Connection lost on the Kandy corridor</h2><Badge className="mt-3" tone={net.online ? 'success' : 'warning'}>{net.online ? 'Connection available' : 'Degraded · offline'}</Badge><p className="mt-3 text-sm text-muted">{field ? 'Continue loading counts, arrivals, delivery outcomes and proof on this device. Keep this browser’s data until synchronization completes.' : 'You can inspect saved information. Reconnect before making planning decisions or confirming store receipts.'}</p><p className="mt-2 text-xs text-muted">Last device sync: {net.lastSync ? fmtClock(net.lastSync) : 'No successful sync recorded yet'}. Cached data may not include recent dispatcher changes.</p><div className="mt-4 flex flex-wrap gap-2"><Link to={field ? `${prefix}/sync` : prefix}><Button variant="secondary">{field ? 'Inspect saved updates' : 'View saved dashboard'}</Button></Link>{simulated && <Button onClick={() => setOffline(false)}>Reconnect demo device</Button>}</div></Card>
      <Card className="p-5"><h2 className="flex items-center gap-2 font-semibold"><BrainCircuit className="size-5 text-brand" /> Predictions cannot be trusted</h2><Badge className="mt-3" tone={mode === 'READY' && net.online ? 'info' : 'warning'}>{!net.online ? 'Offline planning allowances' : MODE_LABELS[mode]}</Badge><p className="mt-3 text-sm text-muted">{mode === 'LOW_CONFIDENCE' ? 'Comparable deliveries are limited in this scenario. Ranges widen; inspect the stop and receiving window before deciding.' : mode === 'STALE' ? 'Inputs are 48 hours old in this scenario. Late probabilities are hidden until the input refresh succeeds.' : mode === 'UNAVAILABLE' ? 'The prediction service is unavailable in this scenario. Continue with saved schedules and fixed handling allowances.' : 'Demo estimates are available. Every prediction is advisory; dispatch remains subject to all operating constraints.'}</p><p className="mt-2 text-xs text-muted">{d.intelligence?.updatedAt ? `Scenario updated ${new Date(d.intelligence.updatedAt).toLocaleString()}.` : 'Demo estimates have not been refreshed.'} A fallback is never displayed as a live AI result.</p><div className="mt-4 flex flex-wrap gap-2">{user.role === 'DISPATCHER' ? <><Link to="/dispatcher/predictions"><Button variant="secondary">Review affected orders</Button></Link><Button disabled={!net.online || mode === 'READY'} onClick={() => { ops('predictionMode', 'READY'); toast('Demo estimates restored') }}>Restore demo estimates</Button></> : <Link to={prefix}><Button variant="secondary">Continue with saved plan</Button></Link>}</div></Card>
      <Card className="p-5"><h2 className="flex items-center gap-2 font-semibold"><PackageX className="size-5 text-attention" /> Proof upload or route update failed</h2><Badge className="mt-3" tone={failed || conflict ? 'warning' : 'neutral'}>{conflict ? 'Route reconciliation needed' : failed ? `${failed} failed updates` : 'No failed updates on this device'}</Badge><p className="mt-3 text-sm text-muted">Delivery records and photos stay queued. Retry the upload instead of repeating the delivery. When a route changes offline, compare the updated stops; completed deliveries are preserved.</p><div className="mt-4 flex flex-wrap gap-2">{field ? <><Link to={`${prefix}/sync`}><Button variant="secondary">Open sync & reconciliation</Button></Link><Button disabled={!net.online || !failed || net.status === 'syncing'} onClick={() => void retry()}>Retry failed updates</Button></> : <Link to={`${prefix}/issues`}><Button variant="secondary">Review reported issues</Button></Link>}</div></Card>
      <Card className="p-5"><h2 className="flex items-center gap-2 font-semibold"><ShieldAlert className="size-5 text-critical" /> Vehicle failure or missing stock</h2><p className="mt-3 text-sm text-muted">{user.role === 'DISPATCHER' ? 'Inspect affected stops, compare compatible recovery vehicles, reassign what can be served, and explain remaining deferrals. Hard capacity and cold-chain restrictions still apply.' : user.role === 'DRIVER' ? 'Stop safely before reporting a vehicle or refrigeration failure. Your dispatcher coordinates remaining deliveries; do not continue a paused route.' : user.role === 'LOADER' ? 'Report missing or damaged items before departure. Keep the load open until the dispatcher resolves the shortfall.' : 'Acknowledge rescheduling notices and report receipt discrepancies. Your dispatcher sees the exception and can respond.'}</p><ul className="mt-3 space-y-2 text-sm">{relevant.slice(0, 3).map((i) => <li key={i.id}>{i.title}</li>)}</ul><Link to={`${prefix}/issues`} className="mt-4 inline-block"><Button variant="secondary">{relevant.length ? 'Open exceptions' : user.role === 'DRIVER' ? 'Report vehicle issue' : 'View issue workspace'}</Button></Link></Card>
    </div>
    <Card className="mt-6"><CardHeader title="Try a failure scenario" eyebrow="Demo controls · changes are labelled and reversible" /><div className="space-y-4 p-5"><Callout title="Test continuity without losing the workflow">Connection and upload simulations affect this browser session/device. Prediction scenarios are shared across role tabs. Return to normal after the walkthrough.</Callout><div className="flex flex-wrap gap-3"><Button variant="secondary" icon={<Wifi className="size-4" />} onClick={() => setOffline(!simulated)}>{simulated ? 'Restore demo connection' : 'Simulate connection loss'}</Button>{field && <Button variant="secondary" onClick={() => useDevice.setState({ flakyUploads: !flaky })}>{flaky ? 'Restore proof uploads' : 'Simulate proof upload failure'}</Button>}</div>{user.role === 'DISPATCHER' && <Field label="Prediction service scenario">{(id) => <Select id={id} value={mode} disabled={!net.online} onChange={(e) => ops('predictionMode', e.target.value as PredictionMode)}>{Object.entries(MODE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>}</Field>}</div></Card>
  </>
}
